### ISSUE TITLE
No Recovery Images Past v114

### ISSUE THREAD

**Issue by luhgarlicbread** [e9x/chrome-versions#3]
It appears to me as if this program doesn't check for recovery images past ChromeOS version v114? 

I am trying to bruteforce reco imgs for the board "dedede". Although, I have not ran the entirety of "npm run bruteforce", running "npm run bruteforce dedede" only got me recovery images up to v114. It would be nice to have the links to all recovery images for all channels (release, dev, canary) of v119 through v121 on the dedede board.

**Comment by e9x** [comment]
this has been fixed with the bruteforcer being completely reworked.

**Comment by luhgarlicbread** [comment]
> this has been fixed with the bruteforcer being completely reworked.

YESSS!!!!!!!! THANK YOU!
