### ISSUE TITLE
Zero Recovery Images Found For Dedede

### ISSUE THREAD

**Issue by luhgarlicbread** [e9x/chrome-versions#4]
Why is the chrome-versions reporting to have found 0 recovery images? I ran the command earlier, but it didn't bruteforce all possible recovery images, see: https://github.com/e9x/chrome-versions/issues/3#issue-2224529244
Here are some of my logs:
win@EthanTiny11:~/chrome-versions$ npm run bruteforce dedede

> chrome-versions@1.0.4 bruteforce
> node --loader=ts-node/esm scripts/bruteforce.ts dedede

(node:10996) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Builds may seem to be out of order, this is expected.
Found 250 builds...
Found 0 images
Fetched images. Inserting...
Requests: { initReq: 10705, realReq: 10705 }
win@EthanTiny11:~/chrome-versions$

**Comment by e9x** [comment]
this has been fixed with the bruteforcer being completely reworked.
